openapi: 3.0.3
info:
  title: VodaHory Statistics
  description: |-
    This is simple database API
  contact:
    name: Ing. Ekaterina Lavrova
    email: lavrova@seznam.cz
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: http://localhost:8080
tags:
  - name: Product
    description: Everything about products for eshop vodahory.cz
  - name: store
    description: All partner companies for eshop vodahory.cz
  - name: user
    description: All registered users
paths:
  products/user/login:
    get:
      tags:
        - user
      summary: Logs user into the system
      description: ''
      operationId: loginUser
      parameters:
        - name: login
          in: query
          description: The user name for login
          required: false
          schema:
            type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                type: string
            application/json:
              schema:
                type: string
        '400':
          description: Invalid username/password supplied
  products/user/logout:
    get:
      tags:
        - user
      summary: Logs out current logged in user session
      description: ''
      operationId: logoutUser
      parameters: [ ]
      responses:
        default:
          description: successful operation
components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
        - companyName
      properties:
        id:
          readOnly: true
          type: integer
          format: int64
          example: 34236599
        name:
          type: string
          example: Mountain Equipment W’s Equinox Vest dámské tílko
        companyName:
          type: string
          example: Mountain Equipment
    Products:
      type: array
      items:
        $ref: '#/components/schemas/Product'